### ISSUE TITLE
Unable to install deathbycaptcha-php-sdk through composer

### ISSUE THREAD

**Issue by abid-majeed54** [juniorb2ss/deathbycaptcha-php-sdk#2]
Hi, i am Unable to install deathbycaptcha-php-sdk through composer.
![screenshot_1](https://user-images.githubusercontent.com/28598269/41274399-151011a4-6dd2-11e8-8f6c-8bd0ff541350.png)

**Comment by juniorb2ss** [comment]
Hi @abid-majeed54 ! Please run a command `composer require juniorb2ss/deathbycaptcha-php-sdk` and get last version of package.
